name: Post

on:
  schedule:
    - cron:  '19 * * * *'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '>=3.10'
          architecture: 'x64'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: >
          python . --twitter --once 
          --twitter-key '${{ secrets.TWITTER_KEY }}' 
          --twitter-secret '${{ secrets.TWITTER_SECRET }}' 
          --twitter-token-key '${{ secrets.TWITTER_TOKEN_KEY }}'
          --twitter-token-secret '${{ secrets.TWITTER_TOKEN_SECRET }}'
          --wiki-url 'https://nickelodeon.fandom.com'
          --twitter-message '{character.name} and {enemy.name} are enemies. (Source: {character.link} and {enemy.link})'