name: Post

on:
  schedule:
    - cron:  '19 * * * *'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - env:
        TWITTER_KEY: ${{ secrets.TWITTER_KEY }}
        TWITTER_SECRET: ${{ secrets.TWITTER_SECRET }}
        TWITTER_TOKEN_KEY: ${{ secrets.TWITTER_TOKEN_KEY }}
        TWITTER_TOKEN_SECRET: ${{ secrets.TWITTER_TOKEN_SECRET }}
        WIKI_URL: 'https://nickelodeon.fandom.com'
        TWITTER_MESSAGE: '{character.name} and {enemy.name} are enemies. (Source: {character.link} and {enemy.link})'
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '>=3.10'
          architecture: 'x64'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python . --twitter --once